### ISSUE TITLE
Generate lighter shades

### ISSUE THREAD

**Issue by mtsweir** [jaclyntan/figma-color-compass#9]
Is there a way to generate even lighter colours? e.g I have a dark base grey #24292E and the lightest generated colour is #E9EAEA, without anything in the #fXXXXX range.

For the moment I take the #E9EAEA value and run the plugin to generate additional shades to achieve the lighter shades.

**Comment by jaclyntan** [comment]
Hi there :)
That's strange, I just used the plugin with #24292E and got #E1E4E8 as the lightest colour with the default settings (8 step value).

But yes, to generate lighter colours all the way to white you can increase the step value (the upper limit is currently 100).

<img width="317" alt="Screen Shot 2021-09-16 at 12 41 31 pm" src="https://user-images.githubusercontent.com/18632934/133550624-36820103-d974-4665-a2ca-5ed7712470ee.png">


Does that work for you?

**Comment by mtsweir** [comment]
Thanks, I was able to get that same value as well, I was previously using a 10 step generation.

I then used #E1E4E8 to generate another 10 shades which I found to be a good enough sample to use.

What's your thoughts on adding the hex code when you hover over each swatch in the app? was just thinking its a handy way to know what each colours hex code is just for reference.

Example:
<img width="332" alt="Screen Shot 2021-09-16 at 4 51 47 PM" src="https://user-images.githubusercontent.com/4976660/133551838-be7e259e-73f6-4f83-b1b7-b7fb281f8d0d.png">

**Comment by jaclyntan** [comment]
Sure that's a great idea. I'll have a look at implementing that in the next update. Thanks for suggesting it!

**Comment by mtsweir** [comment]
Another thought I had was adding dark/light mode palletes as well, that would be a pretty awesome to see.

**Comment by jaclyntan** [comment]
Oh I love that idea! I'll have a go implementing that in the next update. Thank you for the suggestion :)
